# https://github.com/cirosantilli/linux-kernel-module-cheat#travis

language: cpp

sudo: required

script: |
  cd "$TRAVIS_BUILD_DIR"
  # awk: without it, too much stdout (4Mb max)
  # If we ignore stdout: Travis kills job because it spent
  # too long without any new stdout.
  bash -x ./build --download-dependencies --travis |& awk 'NR % 1000 == 0'
  bash -x ./run --kernel-cli 'init=/poweroff.out'
