# This was a noble attempt, but it hits the current 50 minute job timeout :-)
# https://travis-ci.org/cirosantilli/linux-kernel-module-cheat/builds/296454523
# I bet it would likely hit a disk maxout either way if it went on.

language: cpp

sudo: required

install: |
  cd "$TRAVIS_BUILD_DIR"
  bash -x ./configure -t

script: |
  cd "$TRAVIS_BUILD_DIR"
  # -j: I'm unable to install nproc on Travis.
  # TODO why? Is part of coreutils in Ubuntu 16.04:
  # http://manpages.ubuntu.com/manpages/trusty/man1/nproc.1.html
  # which ./configure is installing.
  #
  # awk: without it, too much stdout (4Mb max)
  # If we ignore stdout: Travis kills job because it spent
  # too long without any new stdout.
  #
  # -S otherwise apt-get instlal fails with:
  # The following packages have unmet dependencies:
  # libsdl2-dev : Depends: libegl1-mesa-dev
  #            Depends: libgles2-mesa-dev
  bash -x ./build -j 16 -S |& awk 'NR % 1000 == 0'
  bash -x ./run -e 'init=/poweroff.out' -n
