version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    working_directory: ~/repo
    steps:
      - checkout
      #- restore_cache:
      #    keys:
      #      - v1-dependencies-{{ checksum "requirements.txt" }}
      #      - v1-dependencies-
      #- run:
      #    name: install dependencies
      #    command: |
      #      python3 -m venv venv
      #      . venv/bin/activate
      #      pip install -r requirements.txt
      #- save_cache:
      #    paths:
      #      - ./venv
      #    key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run: env | sort
      - run: pwd
      - run: ls -l
      - run: whoami
      - run: uname -a
      - run: nproc
      - run: date > my-artifact
      - run: ./setup -y
      - run: ./build --arch aarch64 --download-dependencies --nproc 1 gem5
      - store_artifacts:
          path: my-artifact
          destination: my-artifact
